# Generated by Django 4.2.9 on 2024-01-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('AC', 'Action'), ('AV', 'Aventure'), ('AR', 'Arcade'), ('PL', 'Platformer'), ('OT', 'Other')], default='AC', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
