# Generated by Django 4.2.9 on 2024-01-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0002_app_active_functionality_active_game_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='functionality',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
