# Generated by Django 4.2.9 on 2024-01-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_app_link_functionality_link_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='thumbnail',
            field=models.ImageField(upload_to='facade/templates/facade/img/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='thumbnail',
            field=models.ImageField(upload_to='facade/templates/facade/img/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(upload_to='facade/templates/facade/img/thumbnail/'),
        ),
    ]
