# Generated by Django 4.2.15 on 2024-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0005_multi_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='thumbnail',
            field=models.ImageField(upload_to='img/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='thumbnail',
            field=models.ImageField(upload_to='img/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(upload_to='img/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='multi_player',
            name='thumbnail',
            field=models.ImageField(upload_to='img/thumbnail/'),
        ),
    ]
