# Generated by Django 4.2.15 on 2024-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cipher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('shift', models.IntegerField(default=0)),
                ('keyword', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
