# Generated by Django 4.2.15 on 2024-09-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cipher',
        ),
    ]
